# Generated by Django 3.0.2 on 2020-01-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
