# Generated by Django 3.0.2 on 2020-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20200119_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
